### ISSUE TITLE
Precedence operators to resolve S/R conflicts

### ISSUE THREAD

**Issue by kivikakk** [goffrie/plex#12]
This isn't a feature request, more feeling out: would you be interested in a PR that added precedence operators to automatically solve shift–reduce conflicts? (per bison's `%left` / `%right` / `%nonassoc`) If so, I might give it a shot. (No guarantees I'm actually capable of it!)

**Comment by goffrie** [comment]
There's already some support for this, though undocumented, haha. Look for
"overriding" and "no_reduce".

**Comment by goffrie** [comment]
See https://github.com/rudi-c/cs444-java-compiler-in-rust/blob/master/ast/src/parser.rs for an old example of how I used them. If you want to improve the interface or make them more general, or whatever, that would be great!

**Comment by kivikakk** [comment]
Great, will look at this tonight! Thanks :)

**Comment by Addisonbean** [comment]
Sorry if this is the wrong place for this, but I am getting a shift reduce conflict, and am unable to figure out how to use these macros to fix it. Here is the code:

```
expr: Expr {
    // #[overriding]
    Ident(var) Equals expr[rhs] => Expr {
        span: span!(),
        node: Expr_::Assign(var, Box::new(rhs)),
    },
    expr[e] LParen RParen => Expr {
        span: span!(),
        node: Expr_::FuncCall(e),
    },
    term[t] => t,
}
```

That second line, the one commented out, was my attempt at trying to solve the error, but that did nothing to fix it. Do you have any idea how I'd use these macros to fix this problem?

Here is the error:

```
error: shift-reduce conflict:
state: expr -> Ident Equals expr •
       expr -> expr • LParen RParen
token: LParen
```

Thank you for your time!

**Comment by Addisonbean** [comment]
The `#[no_reduce(LParen)]` worked great, and then I was able to get it working with out that by looking further into that java compiler link your shared here. Thank you!
