### ISSUE TITLE
The crates.io version seems out of date

### ISSUE THREAD

**Issue by johanmazel** [goffrie/plex#35]
The provided example is compiling with the nightly 70f130954 2019-04-16 by adding missing "crate::" statements.
The last version published on crates.io is 0.2.3. The fixed example does not compile against this version.
Would it be possible to update the version on crates.io?

**Comment by goffrie** [comment]
I published 0.2.4 to match current master.

Note that the example is still using the Rust 2015 edition. I haven't tested whether all the macro business works correctly in the 2018 edition.

**Comment by johanmazel** [comment]
Thank you very much.
